from agents.brain.prompts.structured.structured_prompt import StructuredPrompt
from agents.brain.prompts.structured.software_design_prompt import SoftwareDesignPrompt
from agents.brain.prompts.structured.get_goal_from_file_prompt import GoalBuilderPrompt
from agents.brain.prompts.structured.controller_prompt import ControllerPrompt
from agents.brain.prompts.structured.env_setup_prompt import EnvironmentSetupPrompt