from agents.brain.goal.milestones.software_dev.software_design_milestone import SoftwareDesignMilestone
from agents.brain.goal.milestones.software_dev.environment_milestone import EnvSetupMilestone
from agents.brain.goal.milestones.software_dev.software_dev_milestones import UsageExampleMilestone, UnitTestMilestone, OracleTestMilestone, ConvergenceMilestone